apiVersion: v1
kind: Service
metadata:
  name: kubernetes-demo-netflix
  labels:
    app: netflix
spec:
  selector:
    app: netflix

  ports:
    - port: 80
      targetPort: 80

  type: LoadBalancer
